### ISSUE TITLE
Internal panic @ go_tools/go/pointer.(*analysis).taggedValue()

### ISSUE THREAD

**Issue by april1989** [o2lab/go2#11]
#### test case: 
- /race_checker/tests/grpc_simple.go
- google.golang.org/grpc/interop/client

#### panic trace: 
```go
Internal panic in pointer analysis:
goroutine 1 [running]:
runtime/debug.Stack(0x24, 0x0, 0x0)
        /usr/local/Cellar/go/1.15/libexec/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        /usr/local/Cellar/go/1.15/libexec/src/runtime/debug/stack.go:16 +0x25
github.tamu.edu/April1989/go_tools/go/pointer.AnalyzeWCtx.func1(0xc011f03b20)
        /Users/bozhen/Documents/GO2/go2/go_tools/go/pointer/analysis.go:413 +0x10b
panic(0x12afb20, 0xc01cb969c0)
        /usr/local/Cellar/go/1.15/libexec/src/runtime/panic.go:969 +0x175
github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).taggedValue(0xc00f320000, 0xc000007f6f, 0x28, 0x64, 0xc00a2c8380)
        /Users/bozhen/Documents/GO2/go2/go_tools/go/pointer/gen.go:620 +0x105
github.tamu.edu/April1989/go_tools/go/pointer.(*untagConstraint).solve(0xc022d365a0, 0xc00f320000, 0xc03d8fbec0)
        /Users/bozhen/Documents/GO2/go2/go_tools/go/pointer/solve.go:312 +0xd0
github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).solveConstraints(0xc00f320000, 0xc02003ad40, 0xc03d8fbec0)
        /Users/bozhen/Documents/GO2/go2/go_tools/go/pointer/solve.go:181 +0x166
github.tamu.edu/April1989/go_tools/go/pointer.(*analysis).solve(0xc00f320000)
        /Users/bozhen/Documents/GO2/go2/go_tools/go/pointer/solve.go:67 +0x2d3
github.tamu.edu/April1989/go_tools/go/pointer.AnalyzeWCtx(0xc01b2fe300, 0x0, 0x136f2c0, 0xc01cb969d0)
        /Users/bozhen/Documents/GO2/go2/go_tools/go/pointer/analysis.go:586 +0xdbc
main.doEachMain(0x0, 0xc00f99f620)
        /Users/bozhen/Documents/GO2/go2/go_tools/main/main.go:160 +0x3a5
main.main()
        /Users/bozhen/Documents/GO2/go2/go_tools/main/main.go:108 +0x995
FATA[2021-02-05T10:18:43-06:00] internal error in pointer analysis: not a tagged object: n32623 (please report this bug) 
```

#### reason:
Untagged object in untag constraints (@go2/go_tools/go/pointer/constraint.go:126), 
this type of constraints are created for a concrete type cast (@go2/go_tools/go/pointer/gen.go:758).
The untag constraints that panics is:
``` go
untag n20007 <- n2238.(bool)
```
which is created for the IR statement below:
```go
    t18 = typeassert,ok arg.(bool)                    (value bool, ok bool) //checks whether arg can be cast to bool type; if yes, cast to t18
``` 
Here, ```arg``` is of type ```interface{}``` (we will explain why this is the problem later), and
```go
pts(n2238 : interface{}) = {n4619, ... } 
``` 

The following is the snippet IR of its enclosing function (*fmt.pp).printArg @https://github.com/golang/go/blob/master/src/fmt/print.go):
``` go
10:                                                         switch.next P:1 S:2
	t18 = typeassert,ok arg.(bool)                    (value bool, ok bool)
	t19 = extract t18 #0                                               bool
	t20 = extract t18 #1                                               bool
	if t20 goto 12 else 13
11:                                                    typeswitch.done P:21 S:0
	return
12:                                                     typeswitch.body P:1 S:1
	t21 = (*pp).fmtBool(p, t19, verb)                                    ()
	jump 11
```
The corresponding source code is: 
```go
switch f := arg.(type) {
	case bool:
		p.fmtBool(f, verb) //cast f to bool type 
    ...
```
When it solves the untag constraint for a new object ```n4619``` added into ```pts(n2238)```, 
the constraint solver (@go2/go_tools/go/pointer/solve.go:305) will call function taggedValue (@go2/go_tools/go/pointer/gen.go:616),
to check whether ```n4619``` is a tagged object. If not, panic.

An object is tagged by function makeTagged (@go2/go_tools/go/pointer/gen.go:530) for two conditions:
1. construct an instance of an interface type from a value of a concrete type @go2/go_tools/go/pointer/gen.go:1633
2. all types of reflection-related constraints @go2/go_tools/go/pointer/reflect.go

2 is from reflection (this is not the reason, no matter we include reflection into analysis or not, this panic happens). 
1 is constructed by an ```ssa.MakeInterface``` IR statement. This type of IR statements is created when a type of ```interface{}``` 
or ```interface``` is required in method call parameters.
 
One case is, for example, in function (*google.golang.org/grpc/binarylog/grpc_binarylog_v1.ClientHeader).ProtoReflect() 
(@https://github.com/grpc/grpc-go/blob/b753f4903c1b09ced50ae223b439a771aff798f9/binarylog/grpc_binarylog_v1/binarylog.pb.go#L460)
```go
func (x *ClientHeader) ProtoReflect() protoreflect.Message {
	...
	return mi.MessageOf(x) 
} 
``` 
The last call is to function (*google.golang.org/protobuf/internal/impl.MessageInfo).MessageOf() 
(@https://github.com/protocolbuffers/protobuf-go/blob/f1ac97a4c3faf8af729ff8db5f7b57ca2c7be5d1/internal/impl/message_reflect.go#L380),
which requires a ```interface{}``` type of input parameter:
```go
func (mi *MessageInfo) MessageOf(m interface{}) pref.Message {
	if reflect.TypeOf(m) != mi.GoReflectType {
	...
}
```
Hence, the IR generated for the last call in function ProtoReflect() is:
```go
2:                                                              if.done P:2 S:0
	t7 = make interface{} <- *ClientHeader (x)                  interface{} // THIS IS THE MAKEINTERFACE IR (interface <- struct)
	t8 = (*google.golang.org/protobuf/internal/impl.MessageInfo).MessageOf(t1, t7) google.golang.org/protobuf/reflect/protoreflect.Message
	return t8
```
Another case is similar, but the parameter is of interface type (we will see this case in the next test case).

In the above example, the use of a ```interface{}``` type parameter is directly in the callee function, which can be seen by
IR translator. However, for the panic we encounter, it is quite far from the creation of object and the use of a ```interface{}```
parameter, I guess that is why IR translator did not prepare a MakeInterface IR instruction.

To be specific, in this panic, object ```n4619``` is created by the IR in function (*google.golang.org/grpc.parser).recvMsg() 
(@https://github.com/grpc/grpc-go/blob/938f6e2f7550e542bd78f3b9e8812665db109e02/rpc_util.go#L556): 
```go
 t36 = make []byte t35 t35 
	create n4619 [1]byte for makeslice
	create n4620 byte for makeslice[*]
	localobj[t36] = n4619
```
its corresponding source code is 
```go
msg = make([]byte, int(length))
```
and ```pts(n4619) is canonical : 	([1]byte)```, which is a slice type and will not be tagged.
Since there is no direct target calls using ```n4619``` as parameter with type ```interface{}```,
no MakeInterface instruction is created for this object.

According to golang documentation (@https://pkg.go.dev/golang.org/x/tools@v0.0.0-20201221201019-196535612888/go/pointer),
a slice is an object.
```
Objects include:

- functions and globals;
- variable allocations in the stack frame or heap;
- maps, channels and slices created by calls to make();
- allocations to construct an interface;
- allocations caused by conversions, e.g. []byte(str).
- arrays allocated by calls to append();
```

#### more details
This panic untag constraint is introduced when analyzing function ```(*google.golang.org/protobuf/internal/impl.messageState).WhichOneof```,
and the corresponding call chain is: 
```
(*google.golang.org/protobuf/internal/impl.messageState).WhichOneof
->(*google.golang.org/protobuf/internal/impl.MessageInfo).init
->(*google.golang.org/protobuf/internal/impl.MessageInfo).initOnce
->(*google.golang.org/protobuf/internal/impl.MessageInfo).makeCoderMethods
->google.golang.org/protobuf/internal/impl.makeWeakMessageFieldCoder
->google.golang.org/protobuf/internal/impl.makeWeakMessageFieldCoder$3
->google.golang.org/protobuf/internal/impl.appendMessage
```
All untagged object panics in grpc are due to this reason. When we exclude function ```WhichOneof``` from analysis,
there is no more panic.

#### test case:
- github.com/pingcap/tidb/cmd/benchraw

#### reason: 
```go
untag n185549 <- n35921.(*github.com/pingcap/tidb/store/tikv.btreeItem)
```
The untag constraint comes from function (*github.com/pingcap/tidb/store/tikv.btreeItem).Less(@https://github.com/google/btree/blob/479b5e81b0a93ec038d201b0b33d17db599531d3/btree.go#L888),
with IR statements: 
```go
	t1 = *t0                                                         []byte
	t2 = typeassert other.(*btreeItem)                           *btreeItem
	t3 = &t2.key [#0]                                               *[]byte
```
which corresponds to source code: 
```go
func (a Int) Less(b Item) bool {
	return a < b.(Int)
}
```

The panic happens when solving for the new instance ```n685133```: 
```go
pts(n35921 : github.com/google/btree.Item) = {n685133, ...
```
where ```pts(n685133) is canonical : 	([1]math/big.Word)``` (this is a makeslice).

However, the input of function Less() is an interface type
(@https://github.com/google/btree/blob/479b5e81b0a93ec038d201b0b33d17db599531d3/btree.go#L59): 
```go 
type Item interface { 
	// Less tests whether the current item is less than the given argument.
	//
	// This must provide a strict weak ordering.
	// If !a.Less(b) && !b.Less(a), we treat this to mean a == b (i.e. we can only
	// hold one of either a or b in the tree).
	Less(than Item) bool
}
```
which requires a MakeInterface IR statement. 

### *** current solution ***
Hard code the function ```taggedValue``` to ```taggedValueSpecial``` to bypass all of these types of false constraints.

**Comment by april1989** [comment]
Issue fixed.
